version: '3.5'
services:
  node-app-1:
      image: 192.168.56.11:5000/ashishk/nodeapp:${env.BUILD_ID}
      tty: true
  node-app-2:
      image: 192.168.56.11:5000/ashishk/nodeapp:${env.BUILD_ID}
      tty: true
  node-app-2:
      image: 192.168.56.11:5000/ashishk/nodeapp:${env.BUILD_ID}
      tty: true
  loadbalancer:
      image: server
      tty: true
      links:
          - node-app-1
          - node-app-2
          - node-app-3
      ports:
          - '80:80'
