Vagrant.configure("2") do |config|


    config.vm.define "Jenkins" do |jenkins|
      jenkins.vm.box = "ubuntu/bionic64"
      #jenkins.vm.synced_folder "./data", "/var/lib/jenkins/",type: 'nfs'
        jenkins.vm.provider "virtualbox" do |vb|
          jenkins.vm.network "private_network",ip:'192.168.56.10',:adapter => 2
          jenkins.vm.hostname = 'jenkins.ci'
          vb.name = "Jenkins"
          vb.memory = 1500
          vb.cpus = 1
        end
       jenkins.vm.provision "shell", path: "jenkins-install.sh"
      end
end